<?php

namespace ContainerZnjxa17;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Assets_Command_CompressService extends App_KernelTestContainer
{
    /*
     * Gets the private 'asset_mapper.assets.command.compress' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\CompressAssetsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['asset_mapper.assets.command.compress'] = $instance = new \Symfony\Component\AssetMapper\Command\CompressAssetsCommand(($container->privates['asset_mapper.compressor'] ?? $container->load('getAssetMapper_CompressorService')));

        $instance->setName('assets:compress');
        $instance->setDescription('Pre-compresses files to serve through a web server');

        return $instance;
    }
}
