<?php

namespace ContainerZnjxa17;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $instance->addFixtures([['fixture' => ($container->privates['App\\DataFixtures\\AppFixtures'] ??= new \App\DataFixtures\AppFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\TripFixtures'] ??= new \App\DataFixtures\TripFixtures()), 'groups' => []]]);

        return $instance;
    }
}
