<?php

namespace ContainerZnjxa17;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.QLiKoNQ.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QLiKoNQ.App\\Controller\\HomeController::index()'] = ($container->privates['.service_locator.QLiKoNQ'] ?? $container->load('get_ServiceLocator_QLiKoNQService'))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
