<?php

namespace ContainerZnjxa17;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Repository\TripRepository' shared autowired service.
     *
     * @return \App\Repository\TripRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TripRepository'] = new \App\Repository\TripRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
