<?php

namespace ContainerZnjxa17;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripFixturesService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\DataFixtures\TripFixtures' shared autowired service.
     *
     * @return \App\DataFixtures\TripFixtures
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DataFixtures\\TripFixtures'] = new \App\DataFixtures\TripFixtures();
    }
}
