# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true

    session:
        cookie_secure: auto

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
