# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection:
        enabled: true

    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_hosts: '^.+$'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

