<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13Ee9Ij\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13Ee9Ij/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container13Ee9Ij.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container13Ee9Ij\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \Container13Ee9Ij\App_KernelProdDebugContainer([
    'container.build_hash' => '13Ee9Ij',
    'container.build_id' => '4caf7dc5',
    'container.build_time' => 1751640629,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container13Ee9Ij');
