<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Trip__CLASSMETADATA__' => 0,
'App__Entity__User__CLASSMETADATA__' => 1,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Trip',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'villeDepart' => $o[2],
                        'villeArrivee' => $o[3],
                        'dateDepart' => $o[4],
                        'dateArrivee' => $o[5],
                        'nombrePassagers' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'ville_depart' => 'villeDepart',
                        'ville_arrivee' => 'villeArrivee',
                        'date_depart' => 'dateDepart',
                        'date_arrivee' => 'dateArrivee',
                        'nombre_passagers' => 'nombrePassagers',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'villeDepart' => 'ville_depart',
                        'villeArrivee' => 'ville_arrivee',
                        'dateDepart' => 'date_depart',
                        'dateArrivee' => 'date_arrivee',
                        'nombrePassagers' => 'nombre_passagers',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'trip',
                    ],
                ],
                'idGenerator' => [
                    $o[7],
                ],
                'name' => [
                    'App\\Entity\\Trip',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'datetime',
                    'datetime',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'villeDepart',
                    'villeArrivee',
                    'dateDepart',
                    'dateArrivee',
                    'nombrePassagers',
                ],
                'columnName' => [
                    1 => 'id',
                    'ville_depart',
                    'ville_arrivee',
                    'date_depart',
                    'date_arrivee',
                    'nombre_passagers',
                ],
                'length' => [
                    2 => 255,
                    255,
                ],
                'nullable' => [
                    4 => true,
                    true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'email' => $o[2],
                        'nom' => $o[3],
                        'prenom' => $o[4],
                        'password' => $o[5],
                        'pseudo' => $o[6],
                        'telephone' => $o[7],
                        'adresse' => $o[8],
                        'date_naissance' => $o[9],
                        'photo' => $o[10],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'password' => 'password',
                        'pseudo' => 'pseudo',
                        'telephone' => 'telephone',
                        'adresse' => 'adresse',
                        'date_naissance' => 'date_naissance',
                        'photo' => 'photo',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'password' => 'password',
                        'pseudo' => 'pseudo',
                        'telephone' => 'telephone',
                        'adresse' => 'adresse',
                        'date_naissance' => 'date_naissance',
                        'photo' => 'photo',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                    ],
                ],
                'idGenerator' => [
                    $o[11],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'blob',
                ],
                'fieldName' => [
                    1 => 'id',
                    'email',
                    'nom',
                    'prenom',
                    'password',
                    'pseudo',
                    'telephone',
                    'adresse',
                    'date_naissance',
                    'photo',
                ],
                'columnName' => [
                    1 => 'id',
                    'email',
                    'nom',
                    'prenom',
                    'password',
                    'pseudo',
                    'telephone',
                    'adresse',
                    'date_naissance',
                    'photo',
                ],
                'length' => [
                    2 => 50,
                    50,
                    50,
                    260,
                    50,
                    50,
                    50,
                    50,
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
