controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /login
    controller: App\Controller\LoginController::index

app_homepage:
    path: /
    controller: App\Controller\SomeController::index

