<?php

namespace ContainerH94gLPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7YlgWCTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7YlgWCT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7YlgWCT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\HomeController::home' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::home()', 'getHomeControllerhomeService', true],
            'App\\Controller\\HomeController::searchResults' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::searchResults()', 'getHomeControllersearchResultsService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.3AfLGKv.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\SearchController::search' => ['privates', '.service_locator.rgB06UG.App\\Controller\\SearchController::search()', 'getSearchControllersearchService', true],
            'App\\Controller\\TripController::autocomplete' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::autocomplete()', 'getTripControllerautocompleteService', true],
            'App\\Controller\\TripController::resultat' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::resultat()', 'getTripControllerresultatService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\HomeController:home' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::home()', 'getHomeControllerhomeService', true],
            'App\\Controller\\HomeController:searchResults' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::searchResults()', 'getHomeControllersearchResultsService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.3AfLGKv.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\SearchController:search' => ['privates', '.service_locator.rgB06UG.App\\Controller\\SearchController::search()', 'getSearchControllersearchService', true],
            'App\\Controller\\TripController:autocomplete' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::autocomplete()', 'getTripControllerautocompleteService', true],
            'App\\Controller\\TripController:resultat' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::resultat()', 'getTripControllerresultatService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\HomeController::home' => '?',
            'App\\Controller\\HomeController::searchResults' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\SearchController::search' => '?',
            'App\\Controller\\TripController::autocomplete' => '?',
            'App\\Controller\\TripController::resultat' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\HomeController:home' => '?',
            'App\\Controller\\HomeController:searchResults' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\SearchController:search' => '?',
            'App\\Controller\\TripController:autocomplete' => '?',
            'App\\Controller\\TripController:resultat' => '?',
        ]);
    }
}
