<?php

namespace ContainerH94gLPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rgB06UG.App\Controller\SearchController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rgB06UG.App\\Controller\\SearchController::search()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tripRepository' => ['privates', 'App\\Repository\\TripRepository', 'getTripRepositoryService', true],
        ], [
            'tripRepository' => 'App\\Repository\\TripRepository',
        ]))->withContext('App\\Controller\\SearchController::search()', $container);
    }
}
