<?php

namespace Container9Cr396G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QLiKoNQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QLiKoNQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QLiKoNQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tripRepo' => ['privates', 'App\\Repository\\TripRepository', 'getTripRepositoryService', true],
        ], [
            'tripRepo' => 'App\\Repository\\TripRepository',
        ]);
    }
}
