<?php

namespace ContainerBpiXCkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcEIVhNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FcEIVhN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FcEIVhN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\TripController::autocomplete' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::autocomplete()', 'getTripControllerautocompleteService', true],
            'App\\Controller\\TripController::resultat' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::resultat()', 'getTripControllerresultatService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\TripController:autocomplete' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::autocomplete()', 'getTripControllerautocompleteService', true],
            'App\\Controller\\TripController:resultat' => ['privates', '.service_locator.QLiKoNQ.App\\Controller\\TripController::resultat()', 'getTripControllerresultatService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\TripController::autocomplete' => '?',
            'App\\Controller\\TripController::resultat' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\TripController:autocomplete' => '?',
            'App\\Controller\\TripController:resultat' => '?',
        ]);
    }
}
