<?php

namespace ContainerBpiXCkO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllerautocompleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QLiKoNQ.App\Controller\TripController::autocomplete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QLiKoNQ.App\\Controller\\TripController::autocomplete()'] = ($container->privates['.service_locator.QLiKoNQ'] ?? $container->load('get_ServiceLocator_QLiKoNQService'))->withContext('App\\Controller\\TripController::autocomplete()', $container);
    }
}
