<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnjxa17\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnjxa17/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerZnjxa17.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerZnjxa17\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerZnjxa17\App_KernelTestContainer([
    'container.build_hash' => 'Znjxa17',
    'container.build_id' => '5b466131',
    'container.build_time' => 1751942722,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnjxa17');
