<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGs7Pwoc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGs7Pwoc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGs7Pwoc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGs7Pwoc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGs7Pwoc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gs7Pwoc',
    'container.build_id' => '42757b9a',
    'container.build_time' => 1752022896,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGs7Pwoc');
