<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpzxP7m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpzxP7m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZpzxP7m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZpzxP7m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZpzxP7m\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZpzxP7m',
    'container.build_id' => '08cd5442',
    'container.build_time' => 1752856883,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpzxP7m');
