<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmhN3ao\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmhN3ao/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmhN3ao.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmhN3ao\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZmhN3ao\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZmhN3ao',
    'container.build_id' => 'db7ae95b',
    'container.build_time' => 1752611622,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmhN3ao');
