<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'Homepage' => [
            'js' => [
                '/build/runtime.js',
                '/build/Homepage.js',
            ],
        ],
        'csrf_protection_controller' => [
            'js' => [
                '/build/runtime.js',
                '/build/csrf_protection_controller.js',
            ],
        ],
    ],
],

]];
