<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.a8a970c0.js',
                '/build/app.0a651137.js',
            ],
            'css' => [
                '/build/app.8ee65aba.css',
            ],
        ],
        'Homepage' => [
            'js' => [
                '/build/runtime.a8a970c0.js',
                '/build/Homepage.67bbe711.js',
            ],
        ],
        'csrf_protection_controller' => [
            'js' => [
                '/build/runtime.a8a970c0.js',
                '/build/csrf_protection_controller.5b3ded25.js',
            ],
        ],
    ],
],

]];
